# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c78526c02b6c2e8fedbe39f52b4c1406f38b045b3ee45e6b1af6aa484b19ab9f22b089f5c0356ade82a2688a7db520fc2697b4d22a40825c88ca2500d45b9c0

test:
  secret_key_base: 4b252de97ec9c6567a75ea6cef99c939ea4f42949e918c67bdd519645e53d07e5eeca4b6d4f7b1ffdeeb6b79d716a696c87359dd7691c17bdfd12a222792efee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
